### ISSUE TITLE
The stack won't deploy some times

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-product-s3-email#1]
There is a known bug that AWS is aware of in CF, which makes it that the stack won't deploy when you deal with S3 Events. To mitigate this problem the stack could be split in two.

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-nested-stacks.html
- https://aws.amazon.com/blogs/devops/use-nested-stacks-to-create-reusable-templates-and-support-role-specialization/

# Work around

Right now a work around that works 100% of the time is to remove from the `S3Email` resource this `NotificationConfiguration.LambdaConfigurations`, build the stack, deploy it, and then re-add the removed section, and perform and update on the stack.

This solution works, since we make sure that the Lambdas are in place before we add the events. For some this will work out of the box, it all depends how fast a Lambda will be deployed, and no, the `DependsOn` directive dose nothing - hence the bug.

**Comment by davidgatti** [comment]
I did try the deployment on a fresh AWS account and it worked without a problem. I'm closing this by hoping that AWS fixed this know bug on their side.

**Comment by joshuamsmith** [comment]
When I open deploy script in CloudFormations I get an error.

> Template format error: Unrecognized resource types: [AWS::SES::ReceiptRule, AWS::SES::ReceiptRuleSet]

**Comment by davidgatti** [comment]
Hmm, check if the Region you are in supports SES.

**Comment by joshuamsmith** [comment]
ahhh yeah looks like I'm on us-west-1, but it's only for us-east-1, us-west-2, and eu-west-1.

Odd. Thanks I'll try to deploy it on west-2!!!
________________________________
